allowCompoundWords: true
dictionaries:
  - cpp-compound-words
  - en_US
  - en-gb
  - fullstack
  - git
  - markdown
  - misc
  - node
  - shellscript
  - softwareTerms
  - vim
enableGlobDot: true
features:
  weighted-suggestions: true
globRoot: ${cwd}
ignorePaths:
  - .*ignore
  - .git
  - .github/CODE_OF_CONDUCT.*
  - .vscode/extensions.json
ignoreRegExpList:
  - kuroné?
language: en,ja
useGitignore: true
version: '0.2'
words:
  - curlrc
  - exrc
  - gdefault
  - inputrc
  - kito
  - wgetrc
  - viml
