set background=dark
set backspace=indent,eol,start
set clipboard=unnamed
set cursorline
set encoding=utf-8 nobomb
set exrc
set fileencodings=utf-8,sjis,cp932,euc-jp,iso-2022-jp
set fileformats=unix,dos,mac
set gdefault
set incsearch
set hlsearch
set nocompatible
set ruler
set secure
set shiftwidth=4
set showcmd
set showmatch
set showmode
set tabstop=2
set title
set ttyfast
set wildmenu
syntax on
