allowCompoundWords: true
dictionaries:
  - cpp
  - en_US
  - en-gb
  - fonts
  - git
  - markdown
  - misc
  - powershell
  - softwareTerms
enableGlobDot: true
features:
  weighted-suggestions: true
globRoot: ${cwd}
ignorePaths:
  - .*ignore
  - .git
  - .github/CODE_OF_CONDUCT.*
  - .vscode/extensions.json
  - cspell.config.yml
language: en,eo,ja
useGitignore: true
version: '0.2'
words:
  - imgbotconfig
  - kito
  - kuron
  - kuroné
