allowCompoundWords: true
dictionaries:
  - cpp
  - en_US
  - en-gb
  - eo
  - fonts
  - powershell
enableGlobDot: true
features:
  weighted-suggestions: true
globRoot: ${cwd}
ignorePaths:
  - .*ignore
  - .git
  - .github/CODE_OF_CONDUCT.*
  - .vscode/extensions.json
  - cspell.config.yml
language: en,eo,ja
useGitignore: true
version: '0.2'
words:
  - lysyi3m
  - kito
  - Kuroné
