#!/bin/sh
# -*- mode: sh -*-
# vim: set ft=sh :

set -eu
cd "$(dirname "$0")"

. libs/lib.sh

deploy_with_chmod '.*' '.'
deploy_with_chmod '*' '.gnupg'

GPG_AGENT="gpg-agent.conf"
rm -rf "${HOME}/.gnupg/${GPG_AGENT}"
cp ".gnupg-mac/${GPG_AGENT}" "${HOME}/.gnupg/"
echo "pinentry-program $(which pinentry-mac)" >> "${HOME}/.gnupg/${GPG_AGENT}"

cp -f ./templates/.gitconfig ~/
# git config --global gpg.program $(which gpg)
gpgconf --kill gpg-agent
open schemes/Source\ Code\ X.terminal
