#!/bin/sh
# vim: set ft=sh :

set -eu
cd $(dirname $0)

deploy() {
  NAME=$1
  SRC=$2
  [ $# -ge 3 ] && DST=$3 || DST=$2
  DSTPATH="${HOME}/${DST}"

  mkdir -p "${DSTPATH}"
  find "${SRC}" -depth 1 -type f -name "${NAME}" -print0 | xargs -0 -n1 basename | xargs -I {} rm -f "${DSTPATH}/{}"
  find "${SRC}" -depth 1 -type f -name "${NAME}" -print0 | xargs -0 -n1 basename | xargs -I {} ln -s "$(pwd)/${SRC}/{}" "${DSTPATH}/{}"
}

deploy_with_chmod() {
  NAME=$1
  SRC=$2
  [ $# -ge 3 ] && DST=$3 || DST=$2
  DSTPATH="${HOME}/${DST}"

  mkdir -p "${DSTPATH}"
  chmod 700 "${DSTPATH}"
  deploy "${NAME}" "${SRC}" "${DST}"
}

deploy_with_chmod '.*' '.'
deploy_with_chmod '*' '.gnupg'
deploy_with_chmod '*' '.gnupg-mac' '.gnupg'
deploy_with_chmod '*' 'bin'
deploy '*' '.vscode' 'Library/Application Support/Code/User'

cp -f ./templates/.gitconfig ~/
gpgconf --kill gpg-agent

open schemes/Source\ Code\ X.terminal
