#!/bin/sh
# -*- mode: sh -*-
# vim: set ft=sh :

set -eu
cd "$(cd "$(dirname "$0")"; pwd)"

. libs/lib.sh

deploy_with_chmod '.*' '.'
deploy_with_chmod '*' '.gnupg'

ln -snf "$(pwd)/husky/macos.huskyrc" "${HOME}/.huskyrc"

GPG_AGENT="gpg-agent.conf"
rm -rf "${HOME}/.gnupg/${GPG_AGENT}"
cp ".gnupg-mac/${GPG_AGENT}" "${HOME}/.gnupg/"
echo "pinentry-program $(which pinentry-mac)" >> "${HOME}/.gnupg/${GPG_AGENT}"

cp -f ./templates/.gitconfig ~/
# git config --global gpg.program $(which gpg)
gpgconf --kill gpg-agent
TERMINAL_PROFILE='Source Code X'
open "schemes/${TERMINAL_PROFILE}.terminal"
defaults write com.apple.Terminal 'Default Window Settings' -string "${TERMINAL_PROFILE}"
defaults write com.apple.Terminal 'Startup Window Settings' -string "${TERMINAL_PROFILE}"
# ! NOTE: DO NOT KILLALL! setup.macos may terminate during the process.
