use-agent
personal-cipher-preferences AES256 CAMELLIA256
personal-digest-preferences SHA512 SHA384
cert-digest-algo SHA512
default-preference-list SHA512 SHA384 AES256 CAMELLIA256 ZLIB BZIP2 ZIP Uncompressed
no-emit-version
no-comments
keyid-format 0xlong
